/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_webfolder_otmpfile_TempFile */

#ifndef _Included_io_webfolder_otmpfile_TempFile
#define _Included_io_webfolder_otmpfile_TempFile
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_webfolder_otmpfile_TempFile
 * Method:    create
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_io_webfolder_otmpfile_TempFile_create
  (JNIEnv *, jclass, jstring);

/*
 * Class:     io_webfolder_otmpfile_TempFile
 * Method:    toFileDescriptor
 * Signature: (I)Ljava/io/FileDescriptor;
 */
JNIEXPORT jobject JNICALL Java_io_webfolder_otmpfile_TempFile_toFileDescriptor
  (JNIEnv *, jclass, jint);

/*
 * Class:     io_webfolder_otmpfile_TempFile
 * Method:    linkat
 * Signature: (ILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_io_webfolder_otmpfile_TempFile_linkat
  (JNIEnv *, jclass, jint, jstring);

#ifdef __cplusplus
}
#endif
#endif
